import OpenAI from "openai";
import { AiOutput, AiOutputSchema, GenerateRequest } from "./schema";

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

function addBusinessDays(start: Date, days: number): Date {
  const result = new Date(start);
  let added = 0;
  while (added < days) {
    result.setDate(result.getDate() + 1);
    const dow = result.getDay();
    if (dow !== 0 && dow !== 6) added++;
  }
  return result;
}

function formatDate(d: Date): string {
  return d.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

function buildPrompt(req: GenerateRequest): string {
  const workloadList = req.workloads.join(", ");
  const isSaas = req.deploymentType === "saas";
  const platformLabel = isSaas ? "Commvault Cloud (SaaS)" : "Commvault Software (On-Premises)";
  const docsBaseUrl = "https://documentation.commvault.com/11.42/software/";
  const docsSuffix = isSaas ? "?view=saas" : "";

  const today = new Date();
  const pocStartDate = addBusinessDays(today, 5);
  const pocStartStr = formatDate(pocStartDate);

  return `You are a senior Commvault pre-sales solutions architect preparing a formal Proof of Concept (POC) document for an enterprise customer engagement.

CLIENT: ${req.clientName}
WORKLOADS: ${workloadList}
DEPLOYMENT MODEL: ${platformLabel}

═══════════════════════════════════════════════════════════════
STEP 1 — RESEARCH THE CLIENT
═══════════════════════════════════════════════════════════════

Before generating any content, research and understand the client company:
- What industry does ${req.clientName} operate in?
- What is their core business (digital engineering, financial services, healthcare, manufacturing, etc.)?
- What scale do they operate at (global, regional, enterprise, mid-market)?
- What kind of platforms, applications, or services do they deliver?
- Why would ${workloadList} databases be critical to their business operations?

Use this understanding to write content that is SPECIFIC to ${req.clientName}, not generic.
Every paragraph must reflect the client's actual business context, industry, and operational reality.

═══════════════════════════════════════════════════════════════
STEP 2 — REFERENCE OFFICIAL COMMVAULT DOCUMENTATION
═══════════════════════════════════════════════════════════════

DEPLOYMENT MODEL: ${platformLabel}
DOCUMENTATION BASE: ${docsBaseUrl}
URL SUFFIX: ${docsSuffix}

ALL technical data in this document MUST be sourced from official Commvault documentation for the ${platformLabel} deployment model.
The documentation root is: ${docsBaseUrl}index.html${docsSuffix}

You MUST reference the correct documentation for:
- System requirements, hardware sizing, and component architecture → source from Commvault system requirements pages
- Network ports and firewall rules → source from Commvault network port requirements documentation
- Backup and restore procedures for ${workloadList} → source from the specific workload protection guides
- Prerequisites and agent requirements → source from Commvault agent installation and configuration guides
- Test case scenarios → based on documented backup/restore capabilities for each workload

${isSaas ? `IMPORTANT — SaaS-SPECIFIC RULES:
- This is a Commvault Cloud (SaaS) deployment. The infrastructure is cloud-hosted and managed by Commvault.
- Do NOT include CommServe or MediaAgent in hardware requirements — these are managed by Commvault Cloud.
- Hardware requirements should only list customer-side components (e.g., Access Nodes, Proxies, Agents).
- All documentation URLs MUST include "?view=saas" at the end.
- Scope, prerequisites, and test cases should reflect SaaS-specific workflows (cloud console, SaaS backup policies, cloud storage targets).
- References to on-premises infrastructure management should be excluded.` : `IMPORTANT — SOFTWARE-SPECIFIC RULES:
- This is an on-premises Commvault Software deployment.
- Include all infrastructure components: CommServe, MediaAgent, Access Nodes, Web Console.
- Hardware sizing must include full server specifications.
- Documentation URLs should NOT include any query parameters.`}

═══════════════════════════════════════════════════════════════
STEP 3 — CONTENT DEPTH AND QUALITY REQUIREMENTS
═══════════════════════════════════════════════════════════════

This document will be delivered to senior IT leadership and architecture teams. The content must read as if written by a consulting engagement lead, not generated by a template.

EXECUTIVE SUMMARY (3-4 paragraphs, 250-350 words total):
- Paragraph 1: Describe ${req.clientName}'s business and why ${workloadList} databases are critical to their operations. Be specific to their industry and business model.
- Paragraph 2: Describe the POC engagement — what it validates (application-consistent backups, policy-driven automation, centralized visibility, reliable recovery across failure scenarios including operational errors and cyber-related incidents).
- Paragraph 3: Describe the expected outcomes — predictable recovery, reduced operational complexity, strong security controls, audit-ready management.
- Paragraph 4: Conclude with how successful POC completion provides technical and operational confidence at enterprise scale.

OBJECTIVE (4-5 paragraphs, 400-500 words total):
- Paragraph 1: Describe ${req.clientName}'s competitive landscape and why ${workloadList} databases support revenue-critical platforms. Explain that business risk extends beyond data loss to service disruption, delayed recovery, and regulatory obligations.
- Paragraph 2: Explain why this POC is important — it moves beyond theoretical capability and validates recovery readiness under real operational conditions. It addresses the gap between "having a backup tool" and having confidence that recovery objectives can be met.
- Paragraph 3: Describe the practical validation — onboarding workloads, applying backup policies, executing routine operations, demonstrating scheduled and on-demand execution with clear visibility into job status and reporting.
- Paragraph 4: Describe recovery validation — restoring entire instances for rapid service recovery, selective database restores for targeted incidents, in-place and out-of-place scenarios, verifying restored data usability.
- Paragraph 5: Describe governance validation — centralized administration, role-based access controls, audit trail evidence, compliance readiness. Conclude with overall POC value proposition.

SCOPE — IN SCOPE (8-10 bullet points):
Each bullet must be a complete, detailed sentence describing a specific activity. Examples of the level of detail expected:
- "Installation and configuration of Commvault software components required to protect the in-scope ${workloadList} workload(s)."
- "Onboarding of the identified database instance(s) into the Commvault management console."
- "Configuration of policy-driven backup plans, including scheduled and on-demand execution."
- "Execution and validation of full and incremental backup operations."
- "Monitoring and visibility of backup jobs, status, and completion through centralized reporting."
- "Execution of restore operations, including in-place and out-of-place recovery scenarios."
- "Validation of restore usability for entire instances and selected databases."
- "Demonstration of role-based access controls and administrative governance."

SCOPE — OUT OF SCOPE (8-10 bullet points):
Each bullet must explicitly exclude a specific activity with enough detail to prevent scope ambiguity. Examples:
- "Protection of database platforms other than ${workloadList}."
- "Long-term performance, scalability, or stress testing beyond the defined POC duration."
- "Disaster recovery testing across geographically separated data centers or regions."
- "Integration with external SIEM, ITSM, or automation platforms outside basic visibility."
- "Hardware procurement, storage sizing for production scale, or final architecture design."
- "Backup or recovery of operating system files, application binaries, or non-database data."
- "Security penetration testing, ransomware simulation, or red-team exercises."
- "Production cutover or replacement of existing backup solutions."

SCOPE — ASSUMPTIONS (8-10 bullet points):
Each assumption must be a complete sentence describing a dependency or precondition. Examples:
- "${req.clientName} will provide access to the ${workloadList} environment required for executing the POC."
- "Database versions and operating systems are supported by the Commvault software in scope."
- "Required network connectivity and firewall ports between Commvault components and database servers are available."
- "Necessary database credentials with appropriate privileges for backup and restore operations will be provided."

WORKLOADS IN SCOPE TABLE:
- One row per workload. Be specific about deployment type (On-Premises, Cloud, Hybrid) and location (Data Center, AWS, Azure, etc.).

HARDWARE REQUIREMENTS:
- componentsTable: List realistic Commvault components (CommServe, MediaAgent, Access Nodes, Web Console, etc.) with quantities and roles.
- hardwareSizingTable: Provide realistic CPU, Memory, Storage, and OS specifications for each component. Use enterprise-grade sizing.
- documentationLinks: Select 3-5 links from the VALIDATED LIST below that are most relevant to ${workloadList}. You MUST ONLY use links from this list — do NOT generate or guess URLs.

  VALIDATED DOCUMENTATION LINKS (verified working on documentation.commvault.com/11.42):
  - https://documentation.commvault.com/11.42/software/protecting_databases_with_commvault.html
  - https://documentation.commvault.com/11.42/software/port_requirements_for_commvault.html
  - https://documentation.commvault.com/11.42/software/sql_server.html
  - https://documentation.commvault.com/11.42/software/oracle.html
  - https://documentation.commvault.com/11.42/software/vmware.html
  - https://documentation.commvault.com/11.42/software/hyper_v.html
  - https://documentation.commvault.com/11.42/software/mysql.html
  - https://documentation.commvault.com/11.42/software/postgresql.html
  - https://documentation.commvault.com/11.42/software/sap_hana.html
  - https://documentation.commvault.com/11.42/software/antivirus_exclusions_for_windows.html
  - https://documentation.commvault.com/11.42/software/recommended_antivirus_exclusions_for_unix_and_mac.html

  ${isSaas ? "FOR SAAS: Append ?view=saas to each selected link. Example: https://documentation.commvault.com/11.42/software/sql_server.html?view=saas" : "FOR SOFTWARE: Use the links exactly as listed above, no suffix."}

  IMPORTANT: Do NOT invent or guess documentation URLs. Only use links from the list above.

NETWORKING AND FIREWALL TABLE:
- List all required ports for Commvault communication (8400, 8401, 8403, etc.) with correct protocols and purposes.
- Include database-specific ports for ${workloadList}.

PREREQUISITES TABLE (GLOBAL — not per workload):
- 10-15 rows covering categories: Infrastructure, Network, Database, Security, Storage, Software.
- Each prerequisite must be specific and actionable.
- Customer Responsibility column must clearly state what the customer must provide or configure.

TEST CASES PER WORKLOAD:
- MUST have one testCasesByWorkload entry for EACH workload: ${workloadList}
- Each workload must have 8-12 test cases covering:
  * Backup operations (full, incremental, log)
  * Restore operations (in-place, out-of-place, point-in-time)
  * Policy and scheduling validation
  * Monitoring and reporting
  * Security and access control
  * Edge cases (large databases, concurrent operations)
- "result" field should be "Pending" for all test cases.
- "comments" should describe expected behavior or validation criteria.

TIMELINES PER WORKLOAD:
- MUST have one timelinesByWorkload entry for EACH workload: ${workloadList}
- POC START DATE: ${pocStartStr} (this is today + 5 business days, excluding weekends)
- ALL workloads run IN PARALLEL — they all start on ${pocStartStr}.
- Each workload must have 6-10 timeline rows covering phases:
  * Phase 1: Environment Setup and Validation
  * Phase 2: Installation and Configuration
  * Phase 3: Backup Operations Testing
  * Phase 4: Restore Operations Testing
  * Phase 5: Governance and Reporting Validation
  * Phase 6: Documentation and Handover

DATE AND DURATION RULES (CRITICAL):
- ALL workloads start on ${pocStartStr} — they are executed in parallel, not sequentially.
- ONLY use business days (Monday–Friday). NEVER schedule on Saturday or Sunday.
- Multiple phases/tasks CAN happen on the SAME day. Each task does NOT need a full day.
- Assess the complexity of each workload:
  * Simple workloads (File Server, VM backup, single standard DB): entire POC completes in 1-2 business days.
  * Medium workloads (SQL Server, MySQL, PostgreSQL, Azure VMs): entire POC completes in 2 business days.
  * Complex workloads (SAP HANA, Oracle RAC, Kubernetes, multi-tier apps): entire POC completes in max 3 business days.
- The TOTAL timeline for any single workload must NOT exceed 3 business days.
- Group related tasks on the same day where logical (e.g., setup + installation on Day 1, backup + restore testing on Day 2).
- "date" field must be in format: "DD MMM YYYY" (e.g., "02 Apr 2026").
- "task" must be specific and actionable.

POC CLOSURE AND HANDOVER (2-3 paragraphs, 150-250 words):
- Describe the formal closure process, findings documentation, success criteria review.
- Describe handover deliverables (test results, configuration documentation, recommendations).
- Conclude with next steps for production planning.

═══════════════════════════════════════════════════════════════
STEP 4 — OUTPUT FORMAT
═══════════════════════════════════════════════════════════════

Return ONLY valid JSON (no markdown, no code fences, no commentary) matching this EXACT structure:

{
  "customerName": "string",
  "workloads": ["string"],
  "executiveSummary": "string",
  "objective": "string",
  "scope": {
    "inScope": ["string"],
    "outOfScope": ["string"],
    "assumptions": ["string"]
  },
  "workloadsInScopeTable": [
    { "workloadCategory": "string", "workload": "string", "deploymentType": "string", "location": "string" }
  ],
  "hardwareRequirements": {
    "componentsTable": [
      { "component": "string", "quantity": "number or string", "role": "string" }
    ],
    "hardwareSizingTable": [
      { "component": "string", "cpu": "string", "memory": "string", "storage": "string", "os": "string" }
    ],
    "documentationLinks": ["string (ONLY from the validated list provided above)"]
  },
  "networkingFirewallTable": [
    { "port": "string", "protocol": "string", "purpose": "string" }
  ],
  "prerequisitesTable": [
    { "category": "string", "prerequisite": "string", "customerResponsibility": "string" }
  ],
  "testCasesByWorkload": [
    {
      "workloadName": "string (MUST match exactly one workload from: ${workloadList})",
      "rows": [
        { "testCase": "string", "description": "string", "comments": "string", "result": "Pending" }
      ]
    }
  ],
  "timelinesByWorkload": [
    {
      "workloadName": "string (MUST match exactly one workload from: ${workloadList})",
      "rows": [
        { "phase": "string", "date": "string", "workload": "string", "task": "string" }
      ]
    }
  ],
  "pocClosureAndHandover": "string"
}

CRITICAL RULES:
- testCasesByWorkload MUST have EXACTLY ${req.workloads.length} entries, one for each: ${workloadList}
- timelinesByWorkload MUST have EXACTLY ${req.workloads.length} entries, one for each: ${workloadList}
- prerequisitesTable is a SINGLE GLOBAL table (NOT per-workload)
- All documentation links MUST come from the validated list provided — do NOT generate or guess URLs
- Content must be specific to ${req.clientName} and their industry — NOT generic
- Write at consulting-grade quality suitable for senior IT leadership
- Return ONLY the JSON object, absolutely nothing else`;
}

export async function callAi(req: GenerateRequest, maxRetries = 2): Promise<AiOutput> {
  const prompt = buildPrompt(req);

  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      const response = await openai.chat.completions.create({
        model: process.env.OPENAI_MODEL || "gpt-4o",
        messages: [
          {
            role: "system",
            content:
              "You are a senior Commvault solutions architect. You research client companies thoroughly and produce enterprise-grade, consulting-quality POC documentation. You source all technical data (ports, sizing, prerequisites, procedures) from official Commvault documentation. For SaaS deployments, you reference Commvault Cloud documentation and exclude on-premises infrastructure. For Software deployments, you include full on-premises components. Your output is always valid JSON matching the exact schema requested. You never include markdown formatting, code fences, or commentary outside the JSON.",
          },
          { role: "user", content: prompt },
        ],
        temperature: 0.9,
        max_tokens: 16000,
        response_format: { type: "json_object" },
      });

      const raw = response.choices[0]?.message?.content;
      if (!raw) throw new Error("Empty AI response");

      const parsed = JSON.parse(raw);
      const validated = AiOutputSchema.parse(parsed);
      return validated;
    } catch (err) {
      console.error(`AI attempt ${attempt + 1} failed:`, err instanceof Error ? err.message : err);
      if (attempt === maxRetries) {
        throw new Error(
          `AI failed after ${maxRetries + 1} attempts: ${err instanceof Error ? err.message : "Unknown error"}`
        );
      }
    }
  }

  throw new Error("Unreachable");
}
